# Copyright (C) 2008-2012 AMEE UK Ltd. - http://www.amee.com
# Released as Open Source Software under the BSD 3-Clause license. See LICENSE.txt for details.

production:
  server: live.amee.com
  username: 
  password: 
  cache: rails

development:
  server: stage.amee.com
  username: 
  password: 
  cache: rails
  
test:
  server: stage.amee.com
  username: 
  password: 

