production:
  server: live.amee.com
  username: platform
  password: OoKtNjw13b
  unprivileged_username: platform
  unprivileged_password: OoKtNjw13b
  cache: rails

development:
  server: platform-science.amee.com
  username: aberkeley2
  password: 73f551e5
  unprivileged_username: explorer_unpriv
  unprivileged_password: 3vqcc5sk
  cache: rails
  
test:
  server: platform-science.amee.com
  username: explorer
  password: 3vqcc5sk
  unprivileged_username: explorer_unpriv
  unprivileged_password: 3vqcc5sk

